const MIN_LIFE_SPAN = 10;
const MAX_LIFE_SPAN = 50; // actually 100 + 500
const MAX_NUMBER_OF_BIRDS = 20;
// const WINDOW_WIDTH = window.innerWidth;
// const WINDOW_HEIGHT = window.innerHeight;
const WINDOW_WIDTH = window.innerWidth / 2;
const WINDOW_HEIGHT = window.innerHeight / 2;
const MIN_HEIGHT = 500;
const MIN_WIDTH = 500;
const MAX_MOVEMENT = 5;
const MIN_MOVEMENT = -5;
